package com.example.szwang.wszfirstapp.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HISTORY".
 */
public class History {

    private Long id;
    /** Not-null value. */
    private String historyItem;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public History() {
    }

    public History(Long id) {
        this.id = id;
    }

    public History(Long id, String historyItem) {
        this.id = id;
        this.historyItem = historyItem;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getHistoryItem() {
        return historyItem;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHistoryItem(String historyItem) {
        this.historyItem = historyItem;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
